"""Create initial chat tables

Revision ID: 796f33c47c97
Revises: 
Create Date: 2026-04-17 10:48:22.369638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796f33c47c97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_chat_messages_tournament_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_receiver_id'), 'chat_messages', ['receiver_id'], unique=False)
    op.drop_column('chat_messages', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_messages_receiver_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_tournament_id'), 'chat_messages', ['tournament_id'], unique=False)
    op.drop_column('chat_messages', 'receiver_id')
    # ### end Alembic commands ###
