export const adminModules = [
  {
    path: '',
    name: 'admin-dashboard',
    label: 'Bảng điều khiển',
    section: 'Tổng quan',
    view: 'dashboard',
    badge: 'Live',
    title: 'Bảng điều khiển',
    description: 'Bảng điều khiển tổng quan cho toàn bộ hệ thống quản trị.',
    highlights: ['Quick links', 'Tiến độ phase', 'Trạng thái auth'],
  },
/*
  {
    path: 'profile',
    name: 'admin-profile',
    label: 'Hồ sơ Admin',
    section: 'Tổng quan',
    view: 'profile',
    badge: 'Live',
    title: 'Hồ sơ Admin',
    description: 'Thông tin tài khoản hiện tại lấy từ API /api/players/me.',
    highlights: ['Thông tin user', 'Thông tin player', 'Session hiện tại'],
  },
*/
  {
    path: 'players',
    name: 'admin-players',
    label: 'Vận động viên',
    section: 'Vận hành',
    view: 'players',
    badge: 'Live',
    title: 'Quản lý Vận động viên',
    description: 'Quản lý hồ sơ vận động viên, kỹ năng, khu vực và thống kê thi đấu.',
    highlights: ['Player profile', 'Skill level', 'Win/loss stats'],
  },
  {
    path: 'tournaments',
    name: 'admin-tournaments',
    label: 'Giải đấu',
    section: 'Giải đấu',
    view: 'tournaments',
    badge: 'Live',
    title: 'Quản lý Giải đấu',
    description: 'Danh sách giải đấu, bộ lọc, tạo mới và chỉnh sửa thông tin giải.',
    highlights: ['Create/Edit form', 'Status filter', 'Draw size', 'Location'],
  },
  {
    path: 'registrations',
    name: 'admin-registrations',
    label: 'Danh sách Đăng ký',
    section: 'Giải đấu',
    view: 'registrations',
    badge: 'Live',
    title: 'Danh sách Đăng ký',
    description: 'Duyệt đăng ký thi đấu, theo dõi thanh toán và trạng thái vào main draw.',
    highlights: ['Approval queue', 'Payment filter', 'Tournament filter'],
  },
  {
    path: 'draws',
    name: 'admin-draws',
    label: 'Bốc thăm & Nhánh',
    section: 'Giải đấu',
    view: 'draws',
    badge: 'Live',
    title: 'Bốc thăm & Nhánh',
    description: 'Thiết lập bracket, seed slots, bye slots và luồng nhánh thi đấu.',
    highlights: ['Bracket view', 'Seed placement', 'Manual pairing'],
  },
  {
    path: 'courts',
    name: 'admin-courts',
    label: 'Quản lý Sân',
    section: 'Điều phối',
    view: 'courts',
    badge: 'Live',
    title: 'Quản lý Sân',
    description: 'Quản lý danh sách sân, mặt sân, địa điểm và tình trạng khả dụng.',
    highlights: ['Court list', 'Surface type', 'Availability'],
  },
  {
    path: 'matches',
    name: 'admin-matches',
    label: 'Trận đấu',
    section: 'Điều phối',
    view: 'matches',
    badge: 'Live',
    title: 'Điều phối Trận đấu',
    description: 'Điều hành trận đấu, cập nhật tỷ số, người thắng và referee assignment.',
    highlights: ['Live score', 'Match status', 'Winner selection'],
  },
  {
    path: 'create-match',
    name: 'admin-create-match',
    label: 'Tạo trận thủ công',
    section: 'Điều phối',
    view: 'AdminCreateMatchView',
    badge: 'New',
    title: 'Tạo trận giao hữu / 1vs1',
    description: 'Ghép cặp vận động viên thủ công, chọn sân và lên lịch thi đấu.',
    highlights: ['Manual Matchmaking', 'Player Selection', 'Court Assignment'],
  },
  {
    path: 'schedule',
    name: 'admin-schedule',
    label: 'Lịch trình',
    section: 'Điều phối',
    view: 'schedule',
    badge: 'Live',
    title: 'Lịch trình',
    description: 'Timeline lịch thi đấu theo ngày, sân và khung giờ.',
    highlights: ['Timeline', 'Court assignment', 'Conflict preview'],
  },
  {
    path: 'rankings',
    name: 'admin-rankings',
    label: 'BXH & Điểm số',
    section: 'Điều phối',
    view: 'rankings',
    badge: 'LIVE',
    title: 'Bảng xếp hạng',
    description: 'Bảng xếp hạng và lịch sử biến động ELO theo nhiều bộ lọc.',
    highlights: ['Ranking table', 'ELO history', 'Category filters'],
  },
  {
    path: 'check-in',
    name: 'admin-checkin',
    label: 'Điểm danh QR',
    section: 'Điều phối',
    view: 'checkin',
    badge: 'New',
    title: 'Điểm danh QR',
    description: 'Quét QR của vận động viên để xác nhận tham gia thi đấu tại sân.',
    highlights: ['QR Scanner', 'Real-time validation', 'Attendance tracking'],
  },
  {
    path: 'payments',
    name: 'admin-payments',
    label: 'Thanh toán',
    section: 'Điều phối',
    view: 'payments',
    badge: 'Live',
    title: 'Đối soát Thanh toán',
    description: 'Đối soát các giao dịch thanh toán, kiểm tra trạng thái webhook và hoàn phí.',
    highlights: ['Transaction list', 'Payment status', 'Reconciliation'],
  },
  {
    path: 'logs',
    name: 'admin-logs',
    label: 'Nhật ký hệ thống',
    section: 'Hệ thống',
    view: 'ActivityLogsView',
    badge: 'Live',
    title: 'Nhật ký hệ thống',
    description: 'Truy vết các thay đổi dữ liệu và thao tác của quản trị viên trên toàn hệ thống.',
    highlights: ['Truy vết JSON', 'IP Address Tracker', 'Action Type Filter'],
  },
  {
    path: 'daily-schedule',
    name: 'admin-daily-schedule',
    label: 'Lịch thi đấu ngày',
    section: 'Điều phối',
    view: 'dailySchedule',
    badge: 'Live',
    title: 'Lịch thi đấu ngày',
    description: 'Lịch trình chi tiết theo từng cụm sân và khung giờ hàng ngày.',
    highlights: ['Timeline', 'Court assignment', 'Daily Operations'],
  },
  {
    path: 'calendar',
    name: 'admin-calendar',
    label: 'Lịch tổng quan',
    section: 'Điều phối',
    view: 'calendar',
    badge: 'Live',
    title: 'Lịch tổng quan',
    description: 'Giao diện lịch theo tháng giúp theo dõi mật độ các trận đấu.',
    highlights: ['Monthly View', 'Match Density', 'Status Tracking'],
  },
  {
    path: 'news',
    name: 'admin-news',
    label: 'Tin tức',
    section: 'Hệ thống',
    view: 'news',
    badge: 'New',
    title: 'Quản lý Tin tức',
    description: 'Viết bài, tải ảnh và đăng thông báo giải đấu.',
    highlights: ['Trình soạn thảo', 'Thumbnail', 'Danh mục'],
  },
  {
    path: 'mail-campaign',
    name: 'admin-mail-campaign',
    label: 'Gửi mail hàng loạt',
    section: 'Hệ thống',
    view: 'mailCampaign',
    badge: 'New',
    title: 'Mail Campaign',
    description: 'Soạn template, chọn lịch gửi, ghi log và gửi thông báo hàng loạt đến VĐV.',
    highlights: ['Template presets', 'Schedule send', 'Send logs'],
  }
]


