export const adminModules = [
  {
    path: '',
    name: 'admin-dashboard',
    label: 'Dashboard',
    section: 'Tổng quan',
    view: 'dashboard',
    badge: 'Live',

    title: 'Admin Overview',
    description: 'Bảng điều khiển tổng quan cho toàn bộ hệ thống quản trị.',
    highlights: ['Quick links', 'Tiến độ phase', 'Trạng thái auth'],
  },
  {
    path: 'profile',
    name: 'admin-profile',
    label: 'Profile',
    section: 'Tổng quan',
    view: 'profile',
    badge: 'Live',

    title: 'Admin Profile',
    description: 'Thông tin tài khoản hiện tại lấy từ API /api/players/me.',
    highlights: ['Thông tin user', 'Thông tin player', 'Session hiện tại'],
  },
  {
    path: 'players',
    name: 'admin-players',
    label: 'Players',
    section: 'Vận hành',
    view: 'players',
    badge: 'Live',

    title: 'Player Management',
    description: 'Quản lý hồ sơ vận động viên, kỹ năng, khu vực và thống kê thi đấu.',
    highlights: ['Player profile', 'Skill level', 'Win/loss stats'],
  },
  {
    path: 'tournaments',
    name: 'admin-tournaments',
    label: 'Tournaments',
    section: 'Giải đấu',
    view: 'tournaments',
    badge: 'Live',

    title: 'Tournament Management',
    description: 'Danh sách giải đấu, bộ lọc, tạo mới và chỉnh sửa thông tin giải.',
    highlights: ['Create/Edit form', 'Status filter', 'Draw size', 'Location'],
  },
  {
    path: 'registrations',
    name: 'admin-registrations',
    label: 'Registrations',
    section: 'Giải đấu',
    view: 'registrations',
    badge: 'Live',

    title: 'Registrations Queue',
    description: 'Duyệt đăng ký thi đấu, theo dõi thanh toán và trạng thái vào main draw.',
    highlights: ['Approval queue', 'Payment filter', 'Tournament filter'],
  },
  {
    path: 'draws',
    name: 'admin-draws',
    label: 'Draws',
    section: 'Giải đấu',
    view: 'draws',
    badge: 'Live',

    title: 'Draw Matrix',
    description: 'Thiết lập bracket, seed slots, bye slots và luồng nhánh thi đấu.',
    highlights: ['Bracket view', 'Seed placement', 'Manual pairing'],
  },
  {
    path: 'courts',
    name: 'admin-courts',
    label: 'Courts',
    section: 'Điều phối',
    view: 'courts',
    badge: 'Live',

    title: 'Court Management',
    description: 'Quản lý danh sách sân, mặt sân, địa điểm và tình trạng khả dụng.',
    highlights: ['Court list', 'Surface type', 'Availability'],
  },
  {
    path: 'matches',
    name: 'admin-matches',
    label: 'Matches',
    section: 'Điều phối',
    view: 'matches',
    badge: 'Live',
    title: 'Match Operations',
    description: 'Điều hành trận đấu, cập nhật tỷ số, người thắng và referee assignment.',
    highlights: ['Live score', 'Match status', 'Winner selection'],
  },
  {
    path: 'schedule',
    name: 'admin-schedule',
    label: 'Schedule',
    section: 'Điều phối',
    view: 'schedule',
    badge: 'Live',

    title: 'Schedule',
    description: 'Timeline lịch thi đấu theo ngày, sân và khung giờ.',
    highlights: ['Timeline', 'Court assignment', 'Conflict preview'],
  },
  {
    path: 'rankings',
    name: 'admin-rankings',
    label: 'Rankings',
    section: 'Điều phối',
    view: 'placeholder',
    badge: 'Mock UI',

    title: 'Ranking Center',
    description: 'Bảng xếp hạng và lịch sử biến động ELO theo nhiều bộ lọc.',
    highlights: ['Ranking table', 'ELO history', 'Category filters'],
  },
  {
    path: 'check-in',
    name: 'admin-checkin',
    label: 'Check-in QR',
    section: 'Điều phối',
    view: 'checkin',
    badge: 'New',
    title: 'QR Check-in',
    description: 'Quét QR của vận động viên để xác nhận tham gia thi đấu tại sân.',
    highlights: ['QR Scanner', 'Real-time validation', 'Attendance tracking'],
  },
  {
    path: 'payments',
    name: 'admin-payments',
    label: 'Payments',
    section: 'Điều phối',
    view: 'payments',
    badge: 'Live',
    title: 'Payment Reconciliation',
    description: 'Đối soát các giao dịch thanh toán, kiểm tra trạng thái webhook và hoàn phí.',
    highlights: ['Transaction list', 'Payment status', 'Reconciliation'],
  },
  {
    path: 'logs',
    name: 'admin-logs',
    label: 'Activity Logs',
    section: 'Hệ thống',
    view: 'ActivityLogsView',
    badge: 'Live',
    title: 'System Audit Logs',
    description: 'Truy vết các thay đổi dữ liệu và thao tác của quản trị viên trên toàn hệ thống.',
    highlights: ['Truy vết JSON', 'IP Address Tracker', 'Action Type Filter'],
  },
  {
    path: 'daily-schedule',
    name: 'admin-daily-schedule',
    label: 'Order of Play',
    section: 'Điều phối',
    view: 'dailySchedule',
    badge: 'Live',
    title: 'Điều phối Sân & Giờ',
    description: 'Lịch trình chi tiết theo từng cụm sân và khung giờ hàng ngày.',
    highlights: ['Timeline', 'Court assignment', 'Daily Operations'],
  },
  {
    path: 'calendar',
    name: 'admin-calendar',
    label: 'Calendar',
    section: 'Điều phối',
    view: 'calendar',
    badge: 'Live',
    title: 'Lịch thi đấu tổng quan',
    description: 'Giao diện lịch theo tháng giúp theo dõi mật độ các trận đấu.',
    highlights: ['Monthly View', 'Match Density', 'Status Tracking'],
  },
  {
    path: 'news',
    name: 'admin-news',
    label: 'Tin tức',
    section: 'Hệ thống',
    view: 'news',
    badge: 'New',
    title: 'Quản lý Tin tức',
    description: 'Viết bài, tải ảnh và đăng thông báo giải đấu.',
    highlights: ['Trình soạn thảo', 'Thumbnail', 'Danh mục'],
  }
]


