"""init_full_db

Revision ID: 0d92b4cb3a7a
Revises: 
Create Date: 2026-04-21 19:02:25.607843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d92b4cb3a7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_otps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_otps_expired_at'), 'auth_otps', ['expired_at'], unique=False)
    op.create_index(op.f('ix_auth_otps_id'), 'auth_otps', ['id'], unique=False)
    op.create_index(op.f('ix_auth_otps_is_used'), 'auth_otps', ['is_used'], unique=False)
    op.create_index(op.f('ix_auth_otps_purpose'), 'auth_otps', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_otps_target_email'), 'auth_otps', ['target_email'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_name'), 'chat_rooms', ['name'], unique=False)
    op.create_index(op.f('ix_chat_rooms_type'), 'chat_rooms', ['type'], unique=False)
    op.create_table('courts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('court_name', sa.String(length=120), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('surface_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_court_name'), 'courts', ['court_name'], unique=False)
    op.create_index(op.f('ix_courts_id'), 'courts', ['id'], unique=False)
    op.create_index(op.f('ix_courts_is_active'), 'courts', ['is_active'], unique=False)
    op.create_index(op.f('ix_courts_location_name'), 'courts', ['location_name'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_url')
    )
    op.create_index(op.f('ix_media_assets_entity_id'), 'media_assets', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_assets_entity_type'), 'media_assets', ['entity_type'], unique=False)
    op.create_index(op.f('ix_media_assets_file_type'), 'media_assets', ['file_type'], unique=False)
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_is_active'), 'newsletter_subscribers', ['is_active'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_subscribed_at'), 'newsletter_subscribers', ['subscribed_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_key', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_scope'), 'roles', ['scope'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('gender_division', sa.String(length=20), nullable=False),
    sa.Column('format_type', sa.String(length=20), nullable=False),
    sa.Column('draw_size', sa.Integer(), nullable=False),
    sa.Column('registration_open_at', sa.DateTime(), nullable=True),
    sa.Column('registration_close_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('surface_type', sa.String(length=30), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('entry_fee_team', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tournaments_category_type'), 'tournaments', ['category_type'], unique=False)
    op.create_index(op.f('ix_tournaments_format_type'), 'tournaments', ['format_type'], unique=False)
    op.create_index(op.f('ix_tournaments_gender_division'), 'tournaments', ['gender_division'], unique=False)
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_registration_close_at'), 'tournaments', ['registration_close_at'], unique=False)
    op.create_index(op.f('ix_tournaments_registration_open_at'), 'tournaments', ['registration_open_at'], unique=False)
    op.create_index(op.f('ix_tournaments_start_date'), 'tournaments', ['start_date'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_created_at'), 'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_processed_at'), 'webhook_logs', ['processed_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_processing_status'), 'webhook_logs', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_logs_reference_code'), 'webhook_logs', ['reference_code'], unique=False)
    op.create_index(op.f('ix_webhook_logs_source'), 'webhook_logs', ['source'], unique=False)
    op.create_table('mail_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_campaigns_id'), 'mail_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_mail_campaigns_status'), 'mail_campaigns', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_province'), 'users', ['province'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('old_data_json', sa.Text(), nullable=True),
    sa.Column('new_data_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_is_processed'), 'activity_logs', ['is_processed'], unique=False)
    op.create_index(op.f('ix_activity_logs_module_name'), 'activity_logs', ['module_name'], unique=False)
    op.create_index(op.f('ix_activity_logs_processed_at'), 'activity_logs', ['processed_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('websocket_session_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_delivery_status'), 'notifications', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_sent'), 'notifications', ['is_sent'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_type'), 'notifications', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_websocket_session_id'), 'notifications', ['websocket_session_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('play_hand', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('skill_level', sa.String(length=30), nullable=True),
    sa.Column('preferred_category', sa.String(length=20), nullable=True),
    sa.Column('elo_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_players_deleted_at'), 'players', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_players_elo_points'), 'players', ['elo_points'], unique=False)
    op.create_index(op.f('ix_players_gender'), 'players', ['gender'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_play_hand'), 'players', ['play_hand'], unique=False)
    op.create_index(op.f('ix_players_preferred_category'), 'players', ['preferred_category'], unique=False)
    op.create_index(op.f('ix_players_skill_level'), 'players', ['skill_level'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('published_by', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_breaking_news', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_posts_approved_by'), 'posts', ['approved_by'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_is_breaking_news'), 'posts', ['is_breaking_news'], unique=False)
    op.create_index(op.f('ix_posts_owner_user_id'), 'posts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_posts_publish_at'), 'posts', ['publish_at'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_published_by'), 'posts', ['published_by'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_group', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_index(op.f('ix_settings_data_type'), 'settings', ['data_type'], unique=False)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_is_secret'), 'settings', ['is_secret'], unique=False)
    op.create_index(op.f('ix_settings_setting_group'), 'settings', ['setting_group'], unique=False)
    op.create_index(op.f('ix_settings_updated_by'), 'settings', ['updated_by'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=True),
    sa.Column('team_code', sa.String(length=50), nullable=True),
    sa.Column('team_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )
    op.create_index(op.f('ix_teams_created_by'), 'teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_is_active'), 'teams', ['is_active'], unique=False)
    op.create_index(op.f('ix_teams_team_name'), 'teams', ['team_name'], unique=False)
    op.create_index(op.f('ix_teams_team_type'), 'teams', ['team_type'], unique=False)
    op.create_table('match_challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('challenger_id', sa.BigInteger(), nullable=False),
    sa.Column('challenged_id', sa.BigInteger(), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['challenger_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_challenges_id'), 'match_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_match_challenges_status'), 'match_challenges', ['status'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ranking_target_type', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('gender_division', sa.String(length=20), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('elo_points', sa.Integer(), nullable=False),
    sa.Column('matches_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('losses_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_category_type'), 'rankings', ['category_type'], unique=False)
    op.create_index(op.f('ix_rankings_elo_points'), 'rankings', ['elo_points'], unique=False)
    op.create_index(op.f('ix_rankings_gender_division'), 'rankings', ['gender_division'], unique=False)
    op.create_index(op.f('ix_rankings_id'), 'rankings', ['id'], unique=False)
    op.create_index(op.f('ix_rankings_player_id'), 'rankings', ['player_id'], unique=False)
    op.create_index(op.f('ix_rankings_rank_no'), 'rankings', ['rank_no'], unique=False)
    op.create_index(op.f('ix_rankings_ranking_target_type'), 'rankings', ['ranking_target_type'], unique=False)
    op.create_index(op.f('ix_rankings_region_code'), 'rankings', ['region_code'], unique=False)
    op.create_index(op.f('ix_rankings_team_id'), 'rankings', ['team_id'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('registrant_type', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('seed_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('group_code', sa.String(length=20), nullable=True),
    sa.Column('partner_name', sa.String(length=150), nullable=True),
    sa.Column('partner_phone', sa.String(length=20), nullable=True),
    sa.Column('partner_email', sa.String(length=255), nullable=True),
    sa.Column('partner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('team_members_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_deleted_at'), 'registrations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_registrations_hold_expires_at'), 'registrations', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.create_index(op.f('ix_registrations_partner_user_id'), 'registrations', ['partner_user_id'], unique=False)
    op.create_index(op.f('ix_registrations_payment_status'), 'registrations', ['payment_status'], unique=False)
    op.create_index(op.f('ix_registrations_player_id'), 'registrations', ['player_id'], unique=False)
    op.create_index(op.f('ix_registrations_registered_at'), 'registrations', ['registered_at'], unique=False)
    op.create_index(op.f('ix_registrations_registrant_type'), 'registrations', ['registrant_type'], unique=False)
    op.create_index(op.f('ix_registrations_status'), 'registrations', ['status'], unique=False)
    op.create_index(op.f('ix_registrations_team_id'), 'registrations', ['team_id'], unique=False)
    op.create_index(op.f('ix_registrations_tournament_id'), 'registrations', ['tournament_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('member_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_player_id'), 'team_members', ['player_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('draw_slots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('bracket_position', sa.String(length=30), nullable=False),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('seed_no', sa.Integer(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=False),
    sa.Column('slot_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_slots_bracket_position'), 'draw_slots', ['bracket_position'], unique=False)
    op.create_index(op.f('ix_draw_slots_id'), 'draw_slots', ['id'], unique=False)
    op.create_index(op.f('ix_draw_slots_is_bye'), 'draw_slots', ['is_bye'], unique=False)
    op.create_index(op.f('ix_draw_slots_registration_id'), 'draw_slots', ['registration_id'], unique=False)
    op.create_index(op.f('ix_draw_slots_slot_no'), 'draw_slots', ['slot_no'], unique=False)
    op.create_index(op.f('ix_draw_slots_slot_status'), 'draw_slots', ['slot_status'], unique=False)
    op.create_index(op.f('ix_draw_slots_tournament_id'), 'draw_slots', ['tournament_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_type', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('round_code', sa.String(length=100), nullable=False),
    sa.Column('match_no', sa.Integer(), nullable=False),
    sa.Column('side_a_registration_id', sa.BigInteger(), nullable=True),
    sa.Column('side_b_registration_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_side', sa.String(length=20), nullable=True),
    sa.Column('winner_registration_id', sa.BigInteger(), nullable=True),
    sa.Column('court_id', sa.BigInteger(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_summary', sa.String(length=255), nullable=True),
    sa.Column('result_note', sa.String(length=255), nullable=True),
    sa.Column('best_of_sets', sa.SmallInteger(), nullable=False),
    sa.Column('ended_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('next_match_id', sa.BigInteger(), nullable=True),
    sa.Column('live_stream_url', sa.String(length=500), nullable=True),
    sa.Column('win_reason', sa.String(length=50), nullable=True),
    sa.Column('elo_affected', sa.Boolean(), nullable=False),
    sa.Column('referee_id', sa.BigInteger(), nullable=True),
    sa.Column('set1_a', sa.SmallInteger(), nullable=True),
    sa.Column('set1_b', sa.SmallInteger(), nullable=True),
    sa.Column('set2_a', sa.SmallInteger(), nullable=True),
    sa.Column('set2_b', sa.SmallInteger(), nullable=True),
    sa.Column('set3_a', sa.SmallInteger(), nullable=True),
    sa.Column('set3_b', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_1_a', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_1_b', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_2_a', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_2_b', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_3_a', sa.SmallInteger(), nullable=True),
    sa.Column('tie_break_3_b', sa.SmallInteger(), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=True),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['next_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['side_a_registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['side_b_registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_court_id'), 'matches', ['court_id'], unique=False)
    op.create_index(op.f('ix_matches_deleted_at'), 'matches', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_matches_elo_affected'), 'matches', ['elo_affected'], unique=False)
    op.create_index(op.f('ix_matches_ended_by'), 'matches', ['ended_by'], unique=False)
    op.create_index(op.f('ix_matches_group_id'), 'matches', ['group_id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_match_no'), 'matches', ['match_no'], unique=False)
    op.create_index(op.f('ix_matches_next_match_id'), 'matches', ['next_match_id'], unique=False)
    op.create_index(op.f('ix_matches_round_code'), 'matches', ['round_code'], unique=False)
    op.create_index(op.f('ix_matches_side_a_registration_id'), 'matches', ['side_a_registration_id'], unique=False)
    op.create_index(op.f('ix_matches_side_b_registration_id'), 'matches', ['side_b_registration_id'], unique=False)
    op.create_index(op.f('ix_matches_stage_type'), 'matches', ['stage_type'], unique=False)
    op.create_index(op.f('ix_matches_start_time'), 'matches', ['start_time'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_matches_updated_by'), 'matches', ['updated_by'], unique=False)
    op.create_index(op.f('ix_matches_win_reason'), 'matches', ['win_reason'], unique=False)
    op.create_index(op.f('ix_matches_winner_registration_id'), 'matches', ['winner_registration_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('challenge_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['match_challenges.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_registration_id'), 'payments', ['registration_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('match_progressions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_match_id', sa.BigInteger(), nullable=False),
    sa.Column('to_match_id', sa.BigInteger(), nullable=False),
    sa.Column('target_side', sa.String(length=10), nullable=False),
    sa.Column('source_outcome', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['to_match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_progressions_from_match_id'), 'match_progressions', ['from_match_id'], unique=False)
    op.create_index(op.f('ix_match_progressions_id'), 'match_progressions', ['id'], unique=False)
    op.create_index(op.f('ix_match_progressions_source_outcome'), 'match_progressions', ['source_outcome'], unique=False)
    op.create_index(op.f('ix_match_progressions_target_side'), 'match_progressions', ['target_side'], unique=False)
    op.create_index(op.f('ix_match_progressions_to_match_id'), 'match_progressions', ['to_match_id'], unique=False)
    op.create_table('ranking_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ranking_target_type', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('gender_division', sa.String(length=20), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('points_before', sa.Integer(), nullable=False),
    sa.Column('points_change', sa.Integer(), nullable=False),
    sa.Column('points_after', sa.Integer(), nullable=False),
    sa.Column('rank_before', sa.Integer(), nullable=True),
    sa.Column('rank_after', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_history_category_type'), 'ranking_history', ['category_type'], unique=False)
    op.create_index(op.f('ix_ranking_history_changed_by'), 'ranking_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_ranking_history_created_at'), 'ranking_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_ranking_history_gender_division'), 'ranking_history', ['gender_division'], unique=False)
    op.create_index(op.f('ix_ranking_history_id'), 'ranking_history', ['id'], unique=False)
    op.create_index(op.f('ix_ranking_history_match_id'), 'ranking_history', ['match_id'], unique=False)
    op.create_index(op.f('ix_ranking_history_player_id'), 'ranking_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_ranking_history_points_after'), 'ranking_history', ['points_after'], unique=False)
    op.create_index(op.f('ix_ranking_history_ranking_target_type'), 'ranking_history', ['ranking_target_type'], unique=False)
    op.create_index(op.f('ix_ranking_history_reason'), 'ranking_history', ['reason'], unique=False)
    op.create_index(op.f('ix_ranking_history_region_code'), 'ranking_history', ['region_code'], unique=False)
    op.create_index(op.f('ix_ranking_history_team_id'), 'ranking_history', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_history_team_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_region_code'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_reason'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_ranking_target_type'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_points_after'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_player_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_match_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_gender_division'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_created_at'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_changed_by'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_category_type'), table_name='ranking_history')
    op.drop_table('ranking_history')
    op.drop_index(op.f('ix_match_progressions_to_match_id'), table_name='match_progressions')
    op.drop_index(op.f('ix_match_progressions_target_side'), table_name='match_progressions')
    op.drop_index(op.f('ix_match_progressions_source_outcome'), table_name='match_progressions')
    op.drop_index(op.f('ix_match_progressions_id'), table_name='match_progressions')
    op.drop_index(op.f('ix_match_progressions_from_match_id'), table_name='match_progressions')
    op.drop_table('match_progressions')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_registration_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_matches_winner_registration_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_win_reason'), table_name='matches')
    op.drop_index(op.f('ix_matches_updated_by'), table_name='matches')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_start_time'), table_name='matches')
    op.drop_index(op.f('ix_matches_stage_type'), table_name='matches')
    op.drop_index(op.f('ix_matches_side_b_registration_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_side_a_registration_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_round_code'), table_name='matches')
    op.drop_index(op.f('ix_matches_next_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_no'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_group_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_ended_by'), table_name='matches')
    op.drop_index(op.f('ix_matches_elo_affected'), table_name='matches')
    op.drop_index(op.f('ix_matches_deleted_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_court_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_draw_slots_tournament_id'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_slot_status'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_slot_no'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_registration_id'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_is_bye'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_id'), table_name='draw_slots')
    op.drop_index(op.f('ix_draw_slots_bracket_position'), table_name='draw_slots')
    op.drop_table('draw_slots')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_player_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_registrations_tournament_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_team_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_status'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_registrant_type'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_registered_at'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_player_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_payment_status'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_partner_user_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_hold_expires_at'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_deleted_at'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_rankings_team_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_region_code'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_ranking_target_type'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_rank_no'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_player_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_gender_division'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_elo_points'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_category_type'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_match_challenges_status'), table_name='match_challenges')
    op.drop_index(op.f('ix_match_challenges_id'), table_name='match_challenges')
    op.drop_table('match_challenges')
    op.drop_index(op.f('ix_teams_team_type'), table_name='teams')
    op.drop_index(op.f('ix_teams_team_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_is_active'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_by'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_settings_updated_by'), table_name='settings')
    op.drop_index(op.f('ix_settings_setting_group'), table_name='settings')
    op.drop_index(op.f('ix_settings_is_secret'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_data_type'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_by'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_publish_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_index(op.f('ix_posts_owner_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_breaking_news'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_approved_by'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_players_skill_level'), table_name='players')
    op.drop_index(op.f('ix_players_preferred_category'), table_name='players')
    op.drop_index(op.f('ix_players_play_hand'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_gender'), table_name='players')
    op.drop_index(op.f('ix_players_elo_points'), table_name='players')
    op.drop_index(op.f('ix_players_deleted_at'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_notifications_websocket_session_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_sent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_delivery_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_processed_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_module_name'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_is_processed'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_province'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mail_campaigns_status'), table_name='mail_campaigns')
    op.drop_index(op.f('ix_mail_campaigns_id'), table_name='mail_campaigns')
    op.drop_table('mail_campaigns')
    op.drop_index(op.f('ix_webhook_logs_source'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_reference_code'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_processing_status'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_processed_at'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_created_at'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_start_date'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_registration_open_at'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_registration_close_at'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_gender_division'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_format_type'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_category_type'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_roles_scope'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_newsletter_subscribers_subscribed_at'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_is_active'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_file_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_entity_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_entity_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_courts_location_name'), table_name='courts')
    op.drop_index(op.f('ix_courts_is_active'), table_name='courts')
    op.drop_index(op.f('ix_courts_id'), table_name='courts')
    op.drop_index(op.f('ix_courts_court_name'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_chat_rooms_type'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_name'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_auth_otps_target_email'), table_name='auth_otps')
    op.drop_index(op.f('ix_auth_otps_purpose'), table_name='auth_otps')
    op.drop_index(op.f('ix_auth_otps_is_used'), table_name='auth_otps')
    op.drop_index(op.f('ix_auth_otps_id'), table_name='auth_otps')
    op.drop_index(op.f('ix_auth_otps_expired_at'), table_name='auth_otps')
    op.drop_table('auth_otps')
    # ### end Alembic commands ###
