"""add_tournament_description

Revision ID: 1f26b7c2c32e
Revises: 3280b10e3025
Create Date: 2026-05-15 10:51:02.817412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f26b7c2c32e'
down_revision: Union[str, Sequence[str], None] = '3280b10e3025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
