"""add_tournament_categories

Revision ID: 3280b10e3025
Revises: 0d92b4cb3a7a
Create Date: 2026-05-15 10:22:04.125384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3280b10e3025'
down_revision: Union[str, Sequence[str], None] = '0d92b4cb3a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_categories_id'), 'tournament_categories', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_categories_tournament_id'), 'tournament_categories', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_match_challenges_id'), 'match_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_match_challenges_status'), 'match_challenges', ['status'], unique=False)
    op.add_column('matches', sa.Column('tournament_category_id', sa.BigInteger(), nullable=True))
    op.add_column('matches', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('matches', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_matches_tournament_category_id'), 'matches', ['tournament_category_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'players', ['player_a_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'tournament_categories', ['tournament_category_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'players', ['player_b_id'], ['id'])
    op.add_column('registrations', sa.Column('partner_player_id', sa.BigInteger(), nullable=True))
    op.add_column('registrations', sa.Column('tournament_category_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_registrations_partner_player_id'), 'registrations', ['partner_player_id'], unique=False)
    op.create_index(op.f('ix_registrations_tournament_category_id'), 'registrations', ['tournament_category_id'], unique=False)
    op.create_foreign_key(None, 'registrations', 'players', ['partner_player_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'tournament_categories', ['tournament_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_tournament_category_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_partner_player_id'), table_name='registrations')
    op.drop_column('registrations', 'tournament_category_id')
    op.drop_column('registrations', 'partner_player_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_tournament_category_id'), table_name='matches')
    op.drop_column('matches', 'image_url')
    op.drop_column('matches', 'video_url')
    op.drop_column('matches', 'tournament_category_id')
    op.drop_index(op.f('ix_match_challenges_status'), table_name='match_challenges')
    op.drop_index(op.f('ix_match_challenges_id'), table_name='match_challenges')
    op.drop_index(op.f('ix_tournament_categories_tournament_id'), table_name='tournament_categories')
    op.drop_index(op.f('ix_tournament_categories_id'), table_name='tournament_categories')
    op.drop_table('tournament_categories')
    # ### end Alembic commands ###
