"""add_is_locked_to_registrations

Revision ID: 5d9f83afcf0b
Revises: c3f9d2a8e7b1
Create Date: 2026-06-07 15:52:08.221937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9f83afcf0b'
down_revision: Union[str, Sequence[str], None] = 'c3f9d2a8e7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_registrations_is_locked'), 'registrations', ['is_locked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_is_locked'), table_name='registrations')
    op.drop_column('registrations', 'is_locked')
    # ### end Alembic commands ###
