"""add_show_on_homepage_to_matches

Revision ID: 6c57d82979f8
Revises: 97bbe9e7c4ba
Create Date: 2026-05-26 11:26:32.561824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c57d82979f8'
down_revision: Union[str, Sequence[str], None] = '97bbe9e7c4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('show_on_homepage', sa.Boolean(), nullable=True))
    op.execute("UPDATE matches SET show_on_homepage = FALSE")
    op.alter_column('matches', 'show_on_homepage', nullable=False)
    op.create_index(op.f('ix_matches_show_on_homepage'), 'matches', ['show_on_homepage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_show_on_homepage'), table_name='matches')
    op.drop_column('matches', 'show_on_homepage')
    # ### end Alembic commands ###
