"""add_admin_notes_to_players

Revision ID: 97bbe9e7c4ba
Revises: b62a91f4d8c1
Create Date: 2026-05-26 11:00:31.231111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bbe9e7c4ba'
down_revision: Union[str, Sequence[str], None] = 'b62a91f4d8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'admin_notes')
    # ### end Alembic commands ###
